homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 29.7081
  longitude: -98.4786
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Chicago
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret api_password
  ssl_certificate: /etc/letsencrypt/live/wahasub.duckdns.org/fullchain.pem
  ssl_key: /etc/letsencrypt/live/wahasub.duckdns.org/privkey.pem
  base_url: wahasub.duckdns.org
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr

# SSL Certificate Sensor/Countdown
  - platform: command_line
    name: SSL ETA
    unit_of_measurement: days
    scan_interval: 10800
    command: "ssl-cert-check -b -c /etc/letsencrypt/live/wahasub.duckdns.org/cert.pem | awk '{ print $NF }'"
    
# Honeywell Total Connect Alarm Panel
alarm_control_panel:
  - platform: totalconnect
    username: !secret totalconnect_username
    password: !secret totalconnect_password
    
# Media Player
media_player:
  - platform: plex
  
# Air Purifiers
dyson:
   username: !secret dyson_username
   password: !secret dyson_password
   language: GB
   devices:
    - device_id: NM8-US-HDA0385A
      device_ip: 192.168.136.22
    - device_id: NM8-US-HDA0382A
      device_ip: 192.168.136.23
      
# Z-Wave Component
zwave:
  usb_path: /dev/ttyACM0

# Netatmo Presence Cameras
netatmo:
  api_key: !secret netatmo_api_key
  secret_key: !secret netatmo_secret_key
  username: !secret netatmo_username
  password: !secret netatmo_password
  
# Harmony Hub    
remote:
   - platform: harmony
     name: Harmony Hub LR
     activity: Watch TV
     host: 192.168.136.15
     
   - platform: harmony
     name: Harmony Hub MBR
     activity: Watch TV
     host: 192.168.136.16
     
# Nest Thermostats
nest:
   client_id: !secret nest_client_id
   client_secret: !secret nest_client_secret
   
# Text to speech
tts:
  - platform: google

# Cloud
cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
